# Documentation available at https://expeditor.chef.io/docs/getting-started/
---

pipelines:
 - verify:
    description: Pull Request validation tests
    public: true
 - coverage:
    description: Unit test coverage
    public: false
    trigger: pull_request

slack:
 notify_channel: inspec-notify

github:
 delete_branch_on_merge: true
 minor_bump_labels:
  - "Version: Bump Minor"
 major_bump_labels:
  - "Version: Bump Major"
 version_tag_format: v{{version}}

release_branches:
  - main

changelog:
 categories:
  - "Type: New Feature": "New Features"
  - "Type: Enhancement": "Enhancements"
  - "Type: Bug": "Bug Fixes"

rubygems:
 - train-winrm

subscriptions:
  - workload: project_promoted:{{agent_id}}:*
    actions:
     - built_in:rollover_changelog
     - built_in:publish_rubygems
  - workload: pull_request_merged:{{github_repo}}:{{release_branch}}:*
    actions:
      - built_in:bump_version:
         ignore_labels:
          - "Version: Skip Bump"
          - "Expeditor: Skip All"
      - bash:.expeditor/update_version.sh:
         only_if: built_in:bump_version
      - built_in:update_changelog:
         ignore_labels:
          - "Changelog: Skip Update"
          - "Expeditor: Skip All"
      - built_in:build_gem:
         only_if:
          - built_in:bump_version
